### ISSUE TITLE
Compatibility with AWS Kinesis Aggregator library? 

### ISSUE THREAD

**Issue by canyousayyes** [awslabs/amazon-kinesis-connectors#53]
Hello Team,

I am using this library to store data from Kinesis stream to S3.

I appreciate the overall design of the library, but then I want to aggregate some data (e.g. calculate sum of timespan group by visitor id) before uploading it to S3.

After some googling I come to find another library https://github.com/awslabs/amazon-kinesis-aggregators but I am not sure how to use them together with the connector library.

I guess I should follow the instructions under this section: https://github.com/awslabs/amazon-kinesis-aggregators#integrating-aggregators-into-existing-applications

but where should I put the `aggregate()`, `checkpoint()`, `initialize()`, `shutdown()` calls? For which class(es) should I extend to do so ?

**Comment by IanMeyers** [comment]
Hi Gene,

I'd suggest that you put the logic for aggregators into the IEmitter class that you build for your connected endpoint. This will allow the Connectors architecture of buffering and transforming to still be used. You would then aggregate just before/after the output to the connected data store. Because the IEmitter receives an UnmodifiableBuffer instance, you will want to transform the data into an Aggregators InputEvent type, and use the aggregateEvents method. If you are want to use one of the built in Emitters for S3, you can just extend the basic emitter, do your aggregation call, and then call super.emit().

HTH,

Ian
